library(tidyverse)
library(lubridate)
library(ggplot2)

m5_20 <- read_csv("202005-divvy-tripdata.csv")
m6_20 <- read_csv("202006-divvy-tripdata.csv")
m7_20 <- read_csv("202007-divvy-tripdata.csv")
m8_20 <- read_csv("202008-divvy-tripdata.csv")
m9_20 <- read_csv("202009-divvy-tripdata.csv")
m10_20 <- read_csv("202010-divvy-tripdata.csv")
m11_20 <- read_csv("202011-divvy-tripdata.csv")
m12_20 <- read_csv("202012-divvy-tripdata.csv")
m1_21 <- read_csv("202101-divvy-tripdata.csv")
m2_21 <- read_csv("202102-divvy-tripdata.csv")
m3_21 <- read_csv("202103-divvy-tripdata.csv")
m4_21 <- read_csv("202104-divvy-tripdata.csv")

m4_21 <- m4_21 %>% select(-c(start_station_name, start_station_id, end_station_name, end_station_id))
m3_21 <- m3_21 %>% select(-c(start_station_name, start_station_id, end_station_name, end_station_id))
m2_21 <- m2_21 %>% select(-c(start_station_name, start_station_id, end_station_name, end_station_id))
m1_21 <- m1_21 %>% select(-c(start_station_name, start_station_id, end_station_name, end_station_id))
m12_20 <- m12_20 %>% select(-c(start_station_name, start_station_id, end_station_name, end_station_id))
m11_20 <- m11_20 %>% select(-c(start_station_name, start_station_id, end_station_name, end_station_id))
m10_20 <- m10_20 %>% select(-c(start_station_name, start_station_id, end_station_name, end_station_id))
m9_20 <- m9_20 %>% select(-c(start_station_name, start_station_id, end_station_name, end_station_id))
m8_20 <- m8_20 %>% select(-c(start_station_name, start_station_id, end_station_name, end_station_id))
m7_20 <- m7_20 %>% select(-c(start_station_name, start_station_id, end_station_name, end_station_id))
m6_20 <- m6_20 %>% select(-c(start_station_name, start_station_id, end_station_name, end_station_id))
m5_20 <- m5_20 %>% select(-c(start_station_name, start_station_id, end_station_name, end_station_id))

all_trips <- bind_rows(m5_20, m6_20, m7_20, m8_20, m9_20, m10_20, m11_20, m12_20, m1_21, m2_21, m3_21, m4_21)

table(all_trips$member_casual)  
table(all_trips$rideable_type)

all_trips$date <- as.Date(all_trips$started_at)
all_trips$month <- format(as.Date(all_trips$date), "%m")
all_trips$day <- format(as.Date(all_trips$date), "%d")
all_trips$year <- format(as.Date(all_trips$date), "%Y")
all_trips$day_of_week <- format(as.Date(all_trips$date), "%A")